### ISSUE TITLE
[Find word at cursor] continue from the top of the file if there is no next match

### ISSUE THREAD

**Issue by yzhang-gh** [msafi/xvsc#10]
It is a really good extension that makes life easier!

One suggestion is to let "find next" command to loop back to the first match in the doc after we come to the last match.

---

Another tip I would like to share is to assign this keybinding
```
{
    "key": "f3",
    "command": "findWordAtCursor.next",
    "when": "!findWidgetVisible"
}
```
It has the same logic with original `f3` behavior and at the same time won't conflict with it.

**Comment by msafi** [comment]
Thanks for posting this, I'll be sure to look into it. Thanks!
