### ISSUE TITLE
add findjump "select to"

### ISSUE THREAD

**Issue by johnlindquist** [msafi/xvsc#3]
I _need_ a "jump and select to" option :)

A video of "select to" here: https://youtu.be/yK8eM50DsAY?t=34s

**Comment by msafi** [comment]
I knew that that's what you were gonna request! 😄

I knew you liked that feature, but I literally never used it in IntelliJ's AceJump. I rely more on the expand and contract selection feature.

Anyway, jump-and-select can be implemented. But there are trade offs:

The more jump characters Find-Jump has access to, the fewer keystrokes it needs to highlight matches. The current jump chars are these 

https://github.com/msafi/xvsc/blob/ee63ade714bc83b8682cb1f307631457b48d31fa/findJump/src/associationManager.ts#L12-L26

We have 52 chars. If we use the SHIFT key for jump-and-select, then the capital letters cannot be used as jump chars anymore, so half the jump keys would be gone, which would mean that the user would have to potentially type more for their desired jump location to be highlighted. But that's one way to implement jump-and-select.

Another way to implement jump-and-select would be to introduce a new command, say `findJump.activateWithSelection` that would perform the jump with selection. If `findJump.activate` is bound to `ctrl+;`, `findJump.activateWithSelection` can be bound to `ctrl+shift+;`. This flow maybe less natural but it doesn't reduce the number of jump characters.

From an implementation point of view, I do prefer the second option.

**Comment by johnlindquist** [comment]
A separate command would be perfect. I'm currently using https://marketplace.visualstudio.com/items?itemName=metaseed.metago , so I'm used to the separate command. Your execution of the design/visuals is waaaay better though :)

**Comment by msafi** [comment]
@johnlindquist Okay, I just published version 1.2.0 with the `activateWithSelection` command that creates a selection from the current position to the new position. Hope it works!

**Comment by johnlindquist** [comment]
Sweet, works like a charm ❤️
